import { StyleSheet } from 'react-native';
import { ITEM_H, GUTTER } from './constants';

// Typographie : Inter (chargée dans App.tsx). Une graisse = une variante précise,
// car fontWeight + police custom est peu fiable sur Android.
export const F = {
  light: 'Inter_300Light',
  regular: 'Inter_400Regular',
  semibold: 'Inter_600SemiBold',
  bold: 'Inter_700Bold',
  extrabold: 'Inter_800ExtraBold',
  black: 'Inter_900Black',
};

// Styles partagés de l'app. Système unifié : fond #0a0a0a, cartes #111 (arrondi 20),
// sélecteurs #141414, accent blanc. Garder ces valeurs cohérentes = interface "propre".
export const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0a0a0a' },
  btn: { width: '100%', backgroundColor: '#fff', padding: 15, borderRadius: 16, alignItems: 'center' },
  btnDisabled: { backgroundColor: '#1e1e1e' },
  btnText: { fontSize: 15, fontFamily: F.extrabold, color: '#000' },
  obTopRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 28 },
  obBackArrow: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center' },
  obBackArrowText: { fontSize: 22, color: '#fff' },
  obProgress: { flex: 1, flexDirection: 'row', gap: 6 },
  obProgressBar: { flex: 1, height: 3, borderRadius: 2, backgroundColor: '#222' },
  obProgressBarActive: { backgroundColor: '#fff' },
  splashContainer: { flex: 1, backgroundColor: '#0a0a0a', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 28 },
  splashLogo: { width: 340, height: 118, marginBottom: -16, alignSelf: 'center' },
  splashLoginContent: { flexGrow: 1, paddingHorizontal: 28, paddingTop: 80, paddingBottom: 32, justifyContent: 'center' },
  splashLogoLogin: { width: 220, height: 76, marginBottom: -10 },
  splashTagline: { fontSize: 10, color: '#888', letterSpacing: 3 },
  splashBottom: { position: 'absolute', bottom: 48, left: 28, right: 28 },
  splashLogin: { fontSize: 12, color: '#888', textAlign: 'center', marginTop: 14 },
  splashLoginLink: { color: '#fff', fontFamily: F.bold },
  obContainer: { flex: 1, backgroundColor: '#0a0a0a', paddingTop: 60, paddingHorizontal: 24 },
  // Les zones de tap s'arrêtent à 180px du bas : les boutons et liens du bas restent cliquables.
  obTapZones: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 180, flexDirection: 'row', zIndex: 1 },
  obNextWrap: { marginTop: 'auto' as any, paddingBottom: 36 },
  obTapLeft: { flex: 1 },
  obTapRight: { flex: 1 },
  obLoginLink: { position: 'absolute', bottom: 44, left: 0, right: 0, alignItems: 'center', zIndex: 10 },
  obScreen: { flex: 1, justifyContent: 'space-between', paddingBottom: 40 },
  obBigTitle: { fontSize: 34, fontFamily: F.black, color: '#fff', letterSpacing: -1, lineHeight: 42, marginBottom: 20 },
  obBody: { fontSize: 16, color: '#999', lineHeight: 26, fontFamily: F.regular },
  obBottom: { marginTop: 'auto' as any, paddingTop: 40 },
  screen: { flex: 1 },
  headline: { fontSize: 28, fontFamily: F.black, color: '#fff', letterSpacing: -0.8, marginBottom: 10, lineHeight: 34 },
  subtext: { fontSize: 14, color: '#999', lineHeight: 22, marginBottom: 28, fontFamily: F.regular },
  inputBlock: { marginBottom: 12 },
  inputLabel: { fontSize: 10, color: '#888', letterSpacing: 1.5, fontFamily: F.bold, marginBottom: 6 },
  // Même label, mais isolé entre deux contrôles : il a besoin d'air au-dessus.
  inputLabelSpaced: { marginTop: 22 },
  inputField: { backgroundColor: '#1a1a1a', borderWidth: 1.5, borderColor: '#2a2a2a', borderRadius: 14, padding: 14, fontSize: 14, color: '#fff', fontFamily: F.regular },
  obBackBtn: { paddingVertical: 14, alignItems: 'center' },
  obBackText: { fontSize: 13, color: '#888' },
  legal: { fontSize: 11, color: '#777', textAlign: 'center', marginTop: 12 },
  legalLink: { color: '#888', fontFamily: F.bold },
  // paddingTop vient de l'encoche (useSafeAreaInsets), jamais d'une valeur en dur :
  // 58px était juste sur un iPhone à Dynamic Island et faux partout ailleurs.
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: GUTTER, paddingBottom: 12 },
  headerLogo: { width: 72, height: 26 },
  headerTitle: { fontSize: 17, fontFamily: F.extrabold, color: '#fff' },
  streakBadge: { backgroundColor: '#1e1e1e', borderRadius: 20, paddingHorizontal: 10, paddingVertical: 5, borderWidth: 1, borderColor: '#2a2a2a', flexDirection: 'row', alignItems: 'center', gap: 3 },
  streakFlame: { fontFamily: F.bold },
  streakText: { fontSize: 12, color: '#fff', fontFamily: F.bold },
  feed: { flex: 1, paddingHorizontal: GUTTER, paddingTop: 8 },
  feedTopFade: { position: 'absolute', top: 0, left: 0, right: 0, height: 60 },
  myUpdate: { backgroundColor: '#111', borderRadius: 20, padding: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 },
  myUpdateInfo: { flex: 1 },
  myUpdateTitle: { fontSize: 14, fontFamily: F.extrabold, color: '#fff' },
  myUpdateSub: { fontSize: 12, color: '#888', marginTop: 2 },
  postedBadge: { backgroundColor: '#fff', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 7 },
  postedBadgeText: { fontSize: 12, fontFamily: F.extrabold, color: '#000' },
  feedCard: { backgroundColor: '#111', borderRadius: 20, marginBottom: 16, overflow: 'hidden' },
  // Fond posé sous la photo : le fondu part d'une surface, pas d'un trou noir.
  feedPhotoWrap: { position: 'relative', backgroundColor: '#141414' },
  feedPhoto: { width: '100%', height: 360 },
  feedOverlayTop: { position: 'absolute', top: 0, left: 0, right: 0, paddingBottom: 40 },
  feedOverlayHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 14 },
  feedOverlayBottom: { position: 'absolute', bottom: 0, left: 0, right: 0, paddingTop: 60 },
  feedOverlayProgress: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 14, paddingBottom: 8 },
  feedCaptionOverlay: { fontSize: 13, color: 'rgba(255,255,255,0.85)', paddingHorizontal: 14, paddingBottom: 6, lineHeight: 18 },
  feedNoPhoto: { padding: 16, paddingBottom: 8 },
  feedNoPhotoCaption: { fontSize: 16, color: '#fff', fontFamily: F.semibold, marginTop: 10, marginBottom: 14, lineHeight: 22 },
  cardHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  av: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#2a2a2a', alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: '#333' },
  avImg: { width: 40, height: 40, borderRadius: 20, borderWidth: 1.5, borderColor: '#333' },
  avText: { fontSize: 14, fontFamily: F.extrabold, color: '#fff' },
  cardMeta: { flex: 1 },
  cardName: { fontSize: 14, fontFamily: F.bold, color: '#fff' },
  cardTime: { fontSize: 11, color: 'rgba(255,255,255,0.6)', marginTop: 1 },
  cardMenuBtn: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  progressRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 10 },
  progressBg: { flex: 1, height: 2, backgroundColor: 'rgba(255,255,255,0.15)', borderRadius: 2 },
  progressFill: { height: 2, backgroundColor: '#fff', borderRadius: 2 },
  progressLabel: { fontSize: 11, fontFamily: F.bold, color: '#999' },
  progressLabelOverlay: { fontSize: 11, fontFamily: F.extrabold, color: 'rgba(255,255,255,0.7)' },
  activeReactionsRow: { paddingHorizontal: 14, paddingBottom: 6, flexGrow: 0 },
  actionsRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingBottom: 14, paddingTop: 4, gap: 8 },
  actionBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#1c1c1c', borderRadius: 22, paddingHorizontal: 14, paddingVertical: 8 },
  actionEmoji: { fontSize: 15 },
  actionText: { fontSize: 13, color: '#888', fontFamily: F.semibold },
  rxn: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#1c1c1c', borderRadius: 20, paddingHorizontal: 10, paddingVertical: 5, marginRight: 6, marginBottom: 8 },
  rxnActive: { backgroundColor: '#2a2a2a' },
  rxnEmoji: { fontSize: 14 },
  rxnCount: { fontSize: 12, color: '#888', fontFamily: F.bold },
  emojiPickerRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, paddingHorizontal: 16, paddingBottom: 14, paddingTop: 4 },
  emojiPickerItem: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#1c1c1c', alignItems: 'center', justifyContent: 'center' },
  emojiPickerItemActive: { backgroundColor: '#2a2a2a', borderWidth: 1.5, borderColor: '#fff' },
  emojiPickerItemText: { fontSize: 20 },
  commentRow: { flexDirection: 'row', gap: 10, marginBottom: 16 },
  commentAv: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#2a2a2a', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  commentAvText: { fontSize: 13, fontFamily: F.extrabold, color: '#fff' },
  commentContent: { flex: 1, backgroundColor: '#141414', borderRadius: 14, padding: 10 },
  commentName: { fontSize: 12, fontFamily: F.bold, color: '#fff', marginBottom: 3 },
  commentText: { fontSize: 13, color: '#ccc', lineHeight: 18 },
  commentTime: { fontSize: 10, color: '#888', marginTop: 4 },
  commentInputRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 20, paddingVertical: 12, borderTopWidth: 1, borderTopColor: '#1a1a1a', backgroundColor: '#0a0a0a' },
  commentInput: { flex: 1, backgroundColor: '#1a1a1a', borderWidth: 1.5, borderColor: '#2a2a2a', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 10, fontSize: 14, color: '#fff', maxHeight: 80, fontFamily: F.regular },
  sendBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' },
  sendBtnDisabled: { backgroundColor: '#222' },
  searchBarActive: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#111', borderRadius: 20, padding: 14, marginBottom: 16 },
  searchIcon: { fontSize: 14 },
  searchInput: { flex: 1, fontSize: 15, color: '#fff', fontFamily: F.regular },
  // Plus d'air au-dessus d'un titre qu'en dessous : le titre appartient à ce qui suit.
  sectionTitle: { fontSize: 11, color: '#777', fontFamily: F.bold, textTransform: 'uppercase', letterSpacing: 1.5, marginTop: 22, marginBottom: 10 },
  friendRow: { backgroundColor: '#111', borderRadius: 20, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 8 },
  friendRowAv: { width: 46, height: 46, borderRadius: 23, backgroundColor: '#1e1e1e', alignItems: 'center', justifyContent: 'center' },
  friendRowAvImg: { width: 46, height: 46, borderRadius: 23 },
  friendRowAvActive: { borderWidth: 2, borderColor: '#fff' },
  friendRowAvText: { fontSize: 16, fontFamily: F.extrabold, color: '#fff' },
  friendRowInfo: { flex: 1 },
  friendRowName: { fontSize: 15, fontFamily: F.bold, color: '#fff' },
  friendRowSub: { fontSize: 12, color: '#777', marginTop: 2 },
  friendBadge: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#1e1e1e', alignItems: 'center', justifyContent: 'center' },
  friendBadgeText: { fontSize: 13, color: '#888', fontFamily: F.extrabold },
  addFriendBtn: { backgroundColor: '#fff', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 7 },
  addFriendBtnText: { fontSize: 13, fontFamily: F.extrabold, color: '#000' },
  acceptBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' },
  acceptBtnText: { fontSize: 16, color: '#000', fontFamily: F.extrabold },
  declineBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#1e1e1e', alignItems: 'center', justifyContent: 'center' },
  declineBtnText: { fontSize: 14, color: '#888', fontFamily: F.extrabold },
  statsRow: { flexDirection: 'row', gap: 8, marginBottom: 16 },
  statPill: { flex: 1, backgroundColor: '#111', borderRadius: 20, paddingVertical: 14, paddingHorizontal: 6, alignItems: 'center' },
  statVal: { fontSize: 20, fontFamily: F.black, color: '#fff' },
  statLbl: { fontSize: 9, color: '#888', fontFamily: F.bold, marginTop: 3, textTransform: 'uppercase', letterSpacing: 0 },
  objCard: { backgroundColor: '#111', borderRadius: 20, padding: 18, marginBottom: 12 },
  objCardTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  objCardName: { flex: 1, fontSize: 18, fontFamily: F.extrabold, color: '#fff', marginRight: 8 },
  objCardSub: { fontSize: 12, color: '#888', marginBottom: 14 },
  visBadge: { backgroundColor: '#1e1e1e', borderRadius: 20, paddingHorizontal: 10, paddingVertical: 4 },
  visBadgePublic: { backgroundColor: '#fff' },
  visText: { fontSize: 10, fontFamily: F.bold, color: '#888' },
  visTextPublic: { color: '#000' },
  objProgressRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 14 },
  objProgressBg: { flex: 1, height: 4, backgroundColor: '#222', borderRadius: 4 },
  objProgressFill: { height: 4, backgroundColor: '#fff', borderRadius: 4 },
  objPct: { fontSize: 13, fontFamily: F.extrabold, color: '#fff' },
  updateBtn: { backgroundColor: '#fff', borderRadius: 14, padding: 12, alignItems: 'center' },
  updateBtnText: { fontSize: 13, fontFamily: F.extrabold, color: '#000' },
  addObjBtn: { backgroundColor: '#fff', borderRadius: 20, padding: 16, alignItems: 'center', marginBottom: 12 },
  addObjBtnText: { fontSize: 14, fontFamily: F.extrabold, color: '#000' },
  // Layout nav : 2 pilules + bouton "+" isolé au milieu
  bottomNavSplit: {
    position: 'absolute',
    // `bottom` est posé en ligne depuis l'inset bas : sinon la barre passe
    // sous le home indicator des iPhone récents.
    left: GUTTER,
    right: GUTTER,
    height: 64,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  navPill: {
    flex: 1,
    height: 64,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 6,
    borderRadius: 36,
    overflow: 'visible',
    shadowColor: '#000',
    shadowOpacity: 0.4,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 12,
  },
  navPostStandalone: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#fff',
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 0 },
  },
  // Couche verre de la barre : le rendu (Liquid Glass natif ou blur + reflet)
  // est géré par <GlassSurface />, ici on ne fait que la positionner.
  bottomNavGlass: {
    ...StyleSheet.absoluteFillObject,
  },
  navItem: { flex: 1, alignItems: 'center', justifyContent: 'center', height: 64, gap: 2 },
  // Badge rouge (demandes d'amis en attente) — seul rouge de l'app, code universel "notification"
  navBadge: { position: 'absolute', top: 12, right: '50%' as any, marginRight: -22, minWidth: 16, height: 16, borderRadius: 8, backgroundColor: '#ff3b30', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 3, zIndex: 3 },
  navBadgeText: { color: '#fff', fontSize: 9, fontFamily: F.extrabold },
  // Pastille de verre qui reste DANS la barre (centrée verticalement).
  // Position horizontale animée via translateX + étirement (scaleX) pendant le trajet.
  navActiveBubble: {
    position: 'absolute',
    top: 8,            // (barre 64 - bulle 48) / 2 → centré verticalement
    left: 0,
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  // Verre "clear" par-dessus le verre de la barre : la pastille doit rester lisible
  // même quand le Liquid Glass natif n'est pas dispo.
  navActiveBubbleGlass: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    borderRadius: 24,
  },
  visToggle: { flexDirection: 'row', backgroundColor: '#141414', borderWidth: 1, borderColor: '#222', borderRadius: 18, overflow: 'hidden', marginBottom: 4 },
  visOpt: { flex: 1, paddingVertical: 12, alignItems: 'center', margin: 4, borderRadius: 14 },
  visOptActive: { backgroundColor: '#fff' },
  visOptText: { fontSize: 12, fontFamily: F.bold, color: '#888' },
  visOptTextActive: { color: '#000' },
  // paddingBottom posé en ligne depuis l'inset bas (home indicator).
  ctaContainer: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: GUTTER, backgroundColor: '#0a0a0a' },
  cta: { width: '100%', backgroundColor: '#fff', padding: 16, borderRadius: 18, alignItems: 'center' },
  ctaText: { fontSize: 16, fontFamily: F.extrabold, color: '#000' },
  backBtn: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#1a1a1a', borderWidth: 1, borderColor: '#2a2a2a', alignItems: 'center', justifyContent: 'center' },
  modalContainer: { flex: 1, backgroundColor: '#0a0a0a' },
  // Feuille modale (pageSheet) : elle s'ouvre déjà sous la barre d'état, 56px de
  // padding haut creusaient un vide inutile.
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingTop: 20, paddingBottom: 16, borderBottomWidth: 1, borderBottomColor: '#1a1a1a' },
  modalTitle: { fontSize: 16, fontFamily: F.extrabold, color: '#fff' },
  modalCancel: { fontSize: 14, color: '#888', fontFamily: F.semibold },
  modalSave: { fontSize: 14, color: '#fff', fontFamily: F.extrabold },
  modalBody: { flex: 1, paddingHorizontal: 20, paddingTop: 20 },
  wheelWrap: { height: ITEM_H * 5, backgroundColor: '#111', borderRadius: 18, overflow: 'hidden', marginBottom: 16, position: 'relative' },
  wheelScroll: { flex: 1 },
  wheelSelector: { position: 'absolute', top: ITEM_H * 2, left: 0, right: 0, height: ITEM_H, borderTopWidth: 1, borderBottomWidth: 1, borderColor: '#333', zIndex: 1 },
  wheelItem: { height: ITEM_H, alignItems: 'center', justifyContent: 'center' },
  wheelItemText: { fontSize: 16, color: '#777', fontFamily: F.semibold },
  wheelItemTextActive: { color: '#fff', fontSize: 18, fontFamily: F.extrabold },
  profileHero: { alignItems: 'center', paddingVertical: 24, marginBottom: 8 },
  profileAvatarWrap: { width: 88, height: 88, borderRadius: 44, marginBottom: 12, position: 'relative' },
  profileAvatar: { width: 88, height: 88, borderRadius: 44, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' },
  profileAvatarImg: { width: 88, height: 88, borderRadius: 44 },
  profileAvatarOverlay: { position: 'absolute', bottom: 0, right: 0, width: 28, height: 28, borderRadius: 14, backgroundColor: '#1a1a1a', borderWidth: 2, borderColor: '#0a0a0a', alignItems: 'center', justifyContent: 'center' },
  profileAvatarEditIcon: { fontSize: 12 },
  profileAvatarText: { fontSize: 32, fontFamily: F.black, color: '#000' },
  profileName: { fontSize: 22, fontFamily: F.black, color: '#fff', textAlign: 'center', letterSpacing: -0.5 },
  profileEditHint: { fontSize: 11, color: '#888', textAlign: 'center', marginTop: 4 },
  profileUsername: { fontSize: 13, color: '#888', marginTop: 4 },
  profileMember: { fontSize: 11, color: '#666', marginTop: 4 },
  profileNameEdit: { alignItems: 'center', gap: 10, width: '100%', paddingHorizontal: 20 },
  profileNameInput: { backgroundColor: '#1a1a1a', borderWidth: 1.5, borderColor: '#fff', borderRadius: 14, padding: 12, fontSize: 18, color: '#fff', fontFamily: F.extrabold, textAlign: 'center', width: '100%' },
  profileSaveBtn: { backgroundColor: '#fff', borderRadius: 20, paddingHorizontal: 16, paddingVertical: 8 },
  profileSaveBtnText: { fontSize: 13, fontFamily: F.extrabold, color: '#000' },
  profileCancelBtn: { backgroundColor: '#1e1e1e', borderRadius: 20, paddingHorizontal: 16, paddingVertical: 8 },
  profileCancelBtnText: { fontSize: 13, fontFamily: F.semibold, color: '#888' },
  profileObjRow: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#111', borderRadius: 20, padding: 14, marginBottom: 8 },
  profileObjEmoji: { fontSize: 22 },
  profileObjName: { fontSize: 13, fontFamily: F.bold, color: '#fff', marginBottom: 4 },
  profileObjPct: { fontSize: 13, fontFamily: F.extrabold, color: '#fff' },
  profileUpdateRow: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#111', borderRadius: 20, padding: 14, marginBottom: 8 },
  profileUpdatePhoto: { width: 48, height: 48, borderRadius: 10 },
  profileUpdateCaption: { fontSize: 13, color: '#ccc', fontFamily: F.semibold },
  profileUpdateTime: { fontSize: 11, color: '#888', marginTop: 3 },
  profileProgressBadge: { backgroundColor: '#1e1e1e', borderRadius: 12, paddingHorizontal: 8, paddingVertical: 4 },
  profileProgressBadgeText: { fontSize: 12, fontFamily: F.extrabold, color: '#fff' },
  signOutBtn: { borderWidth: 1.5, borderColor: '#2a2a2a', borderRadius: 16, padding: 14, alignItems: 'center', marginTop: 20, marginBottom: 8 },
  signOutBtnText: { fontSize: 14, fontFamily: F.bold, color: '#888' },
  dangerBtn: { borderWidth: 1.5, borderColor: 'rgba(255,59,48,0.35)', borderRadius: 16, padding: 14, alignItems: 'center', marginBottom: 8 },
  dangerBtnText: { fontSize: 13, fontFamily: F.bold, color: '#ff3b30' },
  // Post screen
  postPhotoZone: { width: '100%', height: 280, backgroundColor: '#111', overflow: 'hidden', position: 'relative' },
  postPhotoImg: { width: '100%', height: '100%' },
  postPhotoChangeBadge: { position: 'absolute', bottom: 12, right: 12, backgroundColor: 'rgba(0,0,0,0.6)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20 },
  postPhotoChangeText: { color: '#fff', fontSize: 12, fontFamily: F.bold },
  postPhotoEmpty: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 6 },
  postPhotoEmptyIcon: { fontSize: 36 },
  postPhotoEmptyText: { fontSize: 15, fontFamily: F.bold, color: '#fff' },
  postPhotoEmptyHint: { fontSize: 12, color: '#777' },
  postBody: { paddingHorizontal: 20, paddingTop: 24 },
  postLabel: { fontSize: 10, color: '#888', letterSpacing: 1.5, fontFamily: F.bold, marginBottom: 12 },
  postEmptyObj: { backgroundColor: '#111', borderRadius: 14, padding: 16, alignItems: 'center', marginBottom: 8 },
  postObjScroll: { marginHorizontal: -20 },
  postObjCard: { width: 120, backgroundColor: '#111', borderRadius: 16, padding: 14, borderWidth: 1.5, borderColor: '#1e1e1e' },
  postObjCardActive: { borderColor: '#fff', backgroundColor: '#1a1a1a' },
  postObjEmoji: { fontSize: 22, marginBottom: 8 },
  postObjTitle: { fontSize: 12, color: '#999', fontFamily: F.semibold, lineHeight: 16 },
  postObjTitleActive: { color: '#fff' },
  postProgressWrap: { flexDirection: 'row', alignItems: 'center', gap: 16, backgroundColor: '#111', borderRadius: 20, padding: 16 },
  postProgressBtn: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#1e1e1e', alignItems: 'center', justifyContent: 'center' },
  postProgressCenter: { flex: 1, alignItems: 'center', gap: 4 },
  postProgressPct: { fontSize: 32, fontFamily: F.black, color: '#fff', letterSpacing: -1 },
  postProgressVal: { fontSize: 12, color: '#888' },
  postProgressBar: { width: '100%', height: 4, backgroundColor: '#222', borderRadius: 2, marginTop: 8 },
  postProgressFill: { height: 4, backgroundColor: '#fff', borderRadius: 2 },
  postCaptionInput: { backgroundColor: '#111', borderRadius: 16, padding: 14, color: '#fff', fontSize: 14, minHeight: 80, textAlignVertical: 'top', lineHeight: 20, fontFamily: F.regular },
  // Suggestions découverte
  suggestScroll: { marginHorizontal: -16 },
  suggestCard: { width: 130, backgroundColor: '#111', borderRadius: 20, padding: 14, alignItems: 'center' },
  suggestAv: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#2a2a2a', alignItems: 'center', justifyContent: 'center', marginBottom: 8 },
  suggestAvImg: { width: 44, height: 44, borderRadius: 22, marginBottom: 8 },
  suggestAvText: { fontSize: 18, fontFamily: F.extrabold, color: '#fff' },
  suggestName: { fontSize: 13, fontFamily: F.bold, color: '#fff', marginBottom: 4, textAlign: 'center' },
  suggestObj: { fontSize: 11, color: '#888', textAlign: 'center', lineHeight: 15, marginBottom: 12 },
  suggestAddBtn: { backgroundColor: '#fff', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 6 },
  suggestAddText: { fontSize: 12, fontFamily: F.extrabold, color: '#000' },
  // Heatmap d'assiduité
  heatGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 3 },
  heatCell: { width: 12, height: 12, borderRadius: 2, backgroundColor: '#1e1e1e' },
  heatCellActive: { backgroundColor: '#fff' },
  // Card objectif unifiée (profil) — progression + heatmap
  objCardProfile: { backgroundColor: '#111', borderRadius: 20, padding: 16, marginBottom: 10, gap: 10 },
  objCardProfileHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  objCardProfileTitle: { flex: 1, fontSize: 15, fontFamily: F.bold, color: '#fff', marginRight: 8 },
  objCardProfilePct: { fontSize: 15, fontFamily: F.black, color: '#fff' },
  objCardProfileFoot: { fontSize: 11, color: '#888', fontFamily: F.semibold, textAlign: 'right', marginTop: -2 },
  // Sélecteur de durée d'engagement
  durationRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 16 },
  durationPill: { paddingHorizontal: 14, paddingVertical: 9, borderRadius: 100, backgroundColor: '#141414', borderWidth: 1.5, borderColor: '#222' },
  durationPillActive: { backgroundColor: '#fff', borderColor: '#fff' },
  durationPillText: { fontSize: 13, fontFamily: F.bold, color: '#888' },
  durationPillTextActive: { color: '#000' },
  // Sélecteur d'emoji (création d'objectif)
  emojiRow: { flexGrow: 0, marginBottom: 16, marginHorizontal: -20 },
  emojiItem: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#141414', borderWidth: 1.5, borderColor: '#222', alignItems: 'center', justifyContent: 'center' },
  emojiItemActive: { backgroundColor: '#fff', borderColor: '#fff' },
  emojiItemText: { fontSize: 20 },
  // Empty state profil (pas d'objectif)
  emptyState: { alignItems: 'center', paddingVertical: 36, paddingHorizontal: 24, gap: 10, marginTop: 8 },
  emptyStateTitle: { fontSize: 18, fontFamily: F.black, color: '#fff', textAlign: 'center', letterSpacing: -0.3, marginTop: 4 },
  emptyStateText: { fontSize: 13, color: '#999', textAlign: 'center', lineHeight: 19, marginBottom: 8 },
  emptyStateBtn: { backgroundColor: '#fff', borderRadius: 16, paddingHorizontal: 22, paddingVertical: 13, marginTop: 4 },
  emptyStateBtnText: { fontSize: 14, fontFamily: F.extrabold, color: '#000' },
  // Skeletons (états de chargement)
  skeletonCard: { backgroundColor: '#111', borderRadius: 20, marginBottom: 16, overflow: 'hidden' },
  skeletonBlock: { backgroundColor: '#1c1c1c', borderRadius: 8 },
});
